### ISSUE TITLE
Morph Factor & Negative Integers

### ISSUE THREAD

**Issue by bwatanabe-CPHC** [Phius-ResearchComittee/REVIVE#11]
Seems we're unable to input a negative integer value in the UI for morph factors. I'm not sure if negative numbers aren't allowed or if the calculation produced a number that it shouldn't have. It seems the '-' is replaced with a zero when you click out of the field.

I assume the software allows for negative integers since the morphing algorithm calculated them that way.

**Screenshots**
![image](https://github.com/user-attachments/assets/9edbe4f9-5512-437d-89fa-850111833bc1)

![image](https://github.com/user-attachments/assets/ee8505aa-3bf8-487f-9d7c-18764ad8fdbd)

ReviveCalc version 24.2

**Comment by amitche8** [comment]
Got it - I will work on this

**Comment by graham-s-wright** [comment]
In the training video there is a text note that the winter morph factors should be negative.

Also I can't copy-paste into the fields.
The precision is limited to two places after the decimal (maybe that's ok, but being able to copy-paste would reduce errors)

**Comment by amitche8** [comment]
This has been fixed in v24.3.0 - the morph factors are now output with 2 decimals, and the input range is -40 to 40
